services:
    apo-web:
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        container_name: apo-web
        build: ./docker/apache
        ports:
            - "80:80"
            - "8000:8000"
        volumes:
            - "./docker/apache/sites-enabled/apo.conf:/etc/apache2/sites-available/apo.conf"
            - "./docker/apache/sites-enabled/apo.conf:/etc/apache2/sites-enabled/apo.conf"
            - ".:/var/www/apo"
        working_dir: /var/www/apo
        networks:
            - new_apo_net

    apo-db:
        container_name: apo-db
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - "./docker/mysql/data/:/var/lib/mysql/"
            - "./docker/mysql/logs:/var/logs/mysql/"
            - "./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql"
        ulimits:
            nofile: # Fix memory leak issue on some systems when LimitCORE=infinity (containerd)
                soft: 1048576
                hard: 1048576
        environment:
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_DATABASE: apoTest
        networks:
            - new_apo_net

networks:
    new_apo_net:
        driver: bridge