services:
    apo-web:
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        container_name: apo-web
        build: ./docker/apache
        ports:
            - "80:80"
            - "8000:8000"
        volumes:
            - "./docker/apache/sites-enabled/apo.conf:/etc/apache2/sites-available/apo.conf"
            - "./docker/apache/sites-enabled/apo.conf:/etc/apache2/sites-enabled/apo.conf"
            - ".:/var/www/apo"
        working_dir: /var/www/apo
        networks:
            - new_apo_net

    apo-db:
        container_name: apo-db
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - "./docker/mysql/data/:/var/lib/mysql/"
            - "./docker/mysql/logs:/var/logs/mysql/"
        ulimits:
            nofile: # Fix memory leak issue on some systems when LimitCORE=infinity (containerd)
                soft: 1048576
                hard: 1048576
        environment:
            MSYQL_HOST: apo-db
            MYSQL_ROOT_PASSWORD: Roo@Toor@123
            MYSQL_DATABASE: apoTest
            MYSQL_USER: apoUser
            MYSQL_PASSWORD: apoPassword
        networks:
            - new_apo_net

networks:
    new_apo_net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.28.0.0/16
                  gateway: 172.28.0.254
